<?php
namespace BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class EventRepository extends EntityRepository
{
  public function findByName($slug)
    {
        $taxonomyClass = $this->_entityName;
        $query = "SELECT tax FROM $taxonomyClass tax
                  WHERE tax.name = :slug
                  ";

        $results = $this->getEntityManager()
            ->createQuery($query)
            ->setParameter("slug", $slug);

        return $results->getOneOrNullResult();
    }

}